name: mypy

on:
    push:
        branches:
            - main
        paths:
            - "**.py"
    pull_request:
        branches:
            - main
        paths:
            - "**.py"

jobs:
    mypy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Install Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.10"

            - name: Install dependencies
              run: |
                  cd backend
                  python -m pip install --upgrade pip
                  pip install uv
                  uv sync

            - name: Run mypy
              run: |
                  cd backend
                  uv run mypy . --explicit-package-bases
